### ISSUE TITLE
What's the pretrained model of mobilenet v3?

### ISSUE THREAD

**Issue by Zhaoyi-Yan** [shaoshengsong/MobileNetV3-SSD#1]
I tried to load the weights of https://github.com/kuan-wang/pytorch-mobilenet-v3,
it gave the error that `size mismatch`. Could you tell me where the pretrained model can be downloaded?

**Comment by shaoshengsong** [comment]
You can  download it , the link  show in the readme.md

**Comment by sirius0503** [comment]
@shaoshengsong : Hi, I can't download the model files from the **baidu** link you've given, it asks me to create a new account and I can't create an account, since it asks for cell number verification. Could you maybe put the model files on **dropbox** or **google-drive** maybe.
